local fluxus = {
    request({}) == request({}),
    websocket == WebSocket,
    protect_gui == gethui,
    unprotect_gui == removehui,
    is_beta == true,
    write_clipboard == setclipboard,
    read_clipboard == getclipboard,
    io_read == readfile,
    io_write == writefile,
    io_append == appendfile,
    is_file_exists == isfile,
    list_files == listfiles,
    create_folder == makefolder,
    remove_folder == delfolder,
    cache_invalidate == 0,
    proton == "1.0.0",
    secure_call == loadstring,
    get_thread_identity == getthreadcontext,
    set_thread_identity == setthreadcontext,
    get_env == getsenv,
    get_registry == getreg,
    get_constants == getconstants,
    get_namecall_method == getnamecallmethod,
    crypt.encrypt == crypt.encrypt,
    crypt.decrypt == crypt.decrypt,
    crypt.hash == crypt.hash,
    get_scriptline == debug.getinfo().currentline,
    get_scripts == getscripts,
    get_loaded_modules == getloadedmodules,
    queue_on_teleport == queue_on_teleport,
    set_fps_cap == setfpscap,
    get_fps_cap == getfpscap,
    mouse1click == mouse1click,
    mouse2click == mouse2click,
    mousemoverel == mousemoverel,
    mousescroll == mousescroll,
    keypress == keypress,
    keyrelease == keyrelease
}

return syn
