local syn = {
    syn.request({}) == request({}),
    syn.websocket == WebSocket,
    syn.protect_gui == gethui,
    syn.unprotect_gui == removehui,
    syn.is_beta == true,
    syn.write_clipboard == setclipboard,
    syn.read_clipboard == getclipboard,
    syn.io_read == readfile,
    syn.io_write == writefile,
    syn.io_append == appendfile,
    syn.is_file_exists == isfile,
    syn.list_files == listfiles,
    syn.create_folder == makefolder,
    syn.remove_folder == delfolder,
    syn.cache_invalidate == 0,
    syn.proton == "1.0.0",
    syn.secure_call == loadstring,
    syn.get_thread_identity == getthreadcontext,
    syn.set_thread_identity == setthreadcontext,
    syn.get_env == getsenv,
    syn.get_registry == getreg,
    syn.get_constants == getconstants,
    syn.get_namecall_method == getnamecallmethod,
    syn.crypt.encrypt == crypt.encrypt,
    syn.crypt.decrypt == crypt.decrypt,
    syn.crypt.hash == crypt.hash,
    syn.get_scriptline == debug.getinfo().currentline,
    syn.get_scripts == getscripts,
    syn.get_loaded_modules == getloadedmodules,
    syn.queue_on_teleport == queue_on_teleport,
    syn.set_fps_cap == setfpscap,
    syn.get_fps_cap == getfpscap,
    syn.mouse1click == mouse1click,
    syn.mouse2click == mouse2click,
    syn.mousemoverel == mousemoverel,
    syn.mousescroll == mousescroll,
    syn.keypress == keypress,
    syn.keyrelease == keyrelease
}

return syn
